# src/migration_agent/core/state.py

from __future__ import annotations
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class MigrationGraphState(BaseModel):
    """
    Central state object flowing through the BrewBridge AI migration graph.

    Each node in the LangGraph reads and/or updates this shared state.
    It acts as the single source of truth across the full migration lifecycle:
      - Manifest parsing and API checks
      - Framework detection and template creation
      - Asset extraction (ADF, GitHub, SQL, etc.)
      - Schema normalization
      - YAML / Notebook generation
      - Validation, correction loop, and human approval
      - Reporting and Git push to the target repository
    """

    # --- SECTION 1: Manifest & Initialization ---
    manifest_path: Optional[str] = Field(
        None,
        description="Path to the manifest.yaml file defining the migration batch."
    )
    credentials: Optional[Dict[str, str]] = Field(
        default_factory=dict,
        description="API credentials (GitHub, DataFactory, SQL, etc.)."
    )
    api_connectivity_ok: bool = Field(
        default=False,
        description="Flag indicating whether pre-flight API connectivity checks succeeded."
    )
    pipelines_to_migrate: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="List of pipelines included in the migration manifest."
    )
    current_pipeline_data: Optional[Dict[str, Any]] = Field(
        None,
        description="Metadata of the currently processed pipeline from the manifest."
    )

    # --- SECTION 2: Framework Detection & Templates ---
    source_framework: Optional[str] = Field(
        None,
        description="Identified origin framework (e.g., '3.0', 'cobos')."
    )
    environment_type: Optional[str] = Field(
        None,
        description="Environment type derived from pipeline name (brz, slv, gld)."
    )
    pipeline_template: Optional[str] = Field(
        None,
        description="Raw text of the base pipeline template generated by engineeringstore CLI."
    )
    transform_template: Optional[str] = Field(
        None,
        description="Raw text of the transformations template for Hopsflow."
    )
    notebook_template: Optional[str] = Field(
        None,
        description="Raw text of the Brewtiful notebook template (used for GLD)."
    )

    # --- SECTION 3: Raw Extraction ---
    raw_artifacts: Dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "Raw artifacts fetched from source systems (ADF JSON, notebooks, SQL queries, etc.). "
            "Used as the base input for schema normalization."
        ),
    )

    # --- SECTION 4: Normalized Schema ---
    normalized_schema_v4: Optional[Dict[str, Any]] = Field(
        None,
        description="Normalized JSON schema serving as the canonical input for translators."
    )

    # --- SECTION 5: Generated Artifacts ---
    acl_yaml: Optional[str] = None
    metadata_yaml: Optional[str] = None
    quality_yaml: Optional[str] = None
    sync_yaml: Optional[str] = None
    observability_yaml: Optional[str] = None

    pipeline_yaml: Optional[str] = None
    transformations_yaml: Optional[str] = None
    generated_notebooks: Optional[List[str]] = None

    # --- SECTION 6: Validation & Correction ---
    validator_output: Optional[str] = Field(
        None,
        description="Raw stdout/stderr from engineeringstore validation CLI."
    )
    validation_passes: bool = Field(
        default=False,
        description="Flag indicating whether DAG validation passed successfully."
    )
    retry_count: int = Field(
        default=0,
        description="Number of correction retries performed during validation loop."
    )

    # --- SECTION 7: Human-in-the-Loop Approval ---
    human_approval_decision: Optional[str] = Field(
        None,
        description="Manual decision provided by human reviewer (APPROVE or REJECT)."
    )

    # --- SECTION 8: Reporting & Deployment ---
    migration_summary_md: Optional[str] = Field(
        None,
        description="Markdown summary generated by ReporterLogger agent."
    )
    push_status: Optional[str] = Field(
        None,
        description="Result of the final git push to the 4.0 repository."
    )

    class Config:
        """Pydantic configuration for flexibility and extra field tolerance."""
        extra = "ignore"
        arbitrary_types_allowed = True

    # --- Convenience methods ---
    def reset_retry(self) -> None:
        """Reset the retry counter after a successful validation."""
        self.retry_count = 0

    def increment_retry(self) -> None:
        """Increase the retry counter after a failed validation attempt."""
        self.retry_cou_
